language: minimal
dist: xenial
services:
  - docker
before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/master/bin/travis-bootstrap | bash
  - cip before-install
install:
  - cip diag
  - cip install
script:
  - cip script
jobs:
  include:
    - env: CIP_TAG=5.30-bullseye   CIP_ENV=TMPDIR=/home/cip/tmp
    - env: CIP_TAG=5.30-bullseye32 CIP_ENV=TMPDIR=/home/cip/tmp
cache:
  directories:
    - "$HOME/.cip"
